
const express = require('express');
const cors = require('cors');
const app = express();
// Enable CORS for all origins
app.use(cors());
// Middleware to parse JSON bodies
app.use(express.json());

let  products = [
    {
      id: 1,
      name: "Women",
      brand: "Chloé",
      title: "Signature Naturelle",
      types: "Eau de Parfum",
      short_description: "Chloé Eau de Parfum Naturelle este o apa de parfum pentru femei care combina forta si spontaneitatea naturii cu spiritul liber al femeii Chloé.",
      long_description: "Chloé Eau de Parfum Naturelle este o apa de parfum pentru femei care combina forta si spontaneitatea naturii cu spiritul liber al femeii Chloé. Fireste eleganta, autentica si constienta, aceasta traieste in perfecta armonie cu natura pe care o pretuieste si care o inspira. Vegana si formulata cu un parfum 100% natural, apa de parfum pentru femei combina ingrediente cultivate in mod responsabil cu alcool de origine naturala pentru a va oferi o prospetime infloritoare pe tot parcursul zilei. Fiecare soapta delicata a trandafirului organic lemnos iconic va va purta intr-o calatorie printr-o atmosfera naturala si linistita. Trandafirul organic, cules manual, este ingredientul cheie al acestui parfum pentru femei, dezvaluind o mireasma cu un caracter aparte, feminin, completat de neroli marocan. Esenta proaspata si delicata de citrice se imbina cu coacazul negru verde stralucitor pentru a dezvalui un caracter puternic, in timp ce notele de baza de cedru adauga o fateta lemnoasa puternica. Mimoza senzuala subliniaza caracterul rotund al parfumului si pune in valoare notele florale.",
      olfactory_note: "Note de varf: Esenta de cedru, Absolut de muguri de coacaze negre Note de mijloc: trandafir organic, esenta de neroli Note de baza: esenta de cedru, absolut de mimoza.",
      price: 416.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwba0054be/images/hi-res/all/SKU/558794_swatch.jpg"
    },
    {
      id: 2,
      name: "Women",
      brand: "Yves Saint Laurent",
      title: "Libre",
      types: "Eau de Parfum",
      short_description: "Noul parfum feminin Libre Le Parfum de la Yves Saint Laurent este declaratia puternica a feminitatii fara limite si neinhibate, aflate intr-o sarbatoare continua, carismatica precum un vultur, renascand ca o pasare Phoenix de fiecare data.",
      long_description: "Maestrii parfumieri Carlos Benaïm si Anne Flipo au selectat cele mai pretioase note si au creat cel mai intens parfum al colectiei Libre, noul Libre Le Parfum, oferind o senzatie arzatorare, condimentata datorita acordului pretios de sofran. Este un omagiu olfactiv adus acestui ingredient pretios, aroma condimentata de sofran rosu numite 'Florile de foc' si celebrate de insusi Yves Saint Laurent. Sticla iconica LIBRE este inspirata de codurile couture YVES SAINT LAURENT: capacul negru lucios cu taietura asimetrica, lanturile aurii ca detaliu al gatului sticlei si logo-ul celebru CASSANDRA YSL auriu",
      olfactory_note: "LIBRE Le Parfum este un foc mistuitor incapsulat in sticla cu accesorii pretioase. O nuanta calda, intensa, reminiscenta a pistilului de sofran.",
      price: 520.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwc541bbaa/images/hi-res/all/SKU/620047_swatch.jpg"
    },
    {
      id: 3,
      name: "Women",
      brand: "Burberry",
      title: "My Burberry Black",
      types: "Eau de Parfum",
      short_description: "Un parfum vibrant care capteaza intreaga esenta a iconicului trandafir!",
      long_description: "Reinterpretare oriental florala a renumitului parfumier Francis Kurkdjian si Christopher Bailey My Burberry Black, inspirat de iconicul trench negru Burberry si de esenta trandafirului, parfumul My Burberry Black capteaza aroma unei gradini londoneze la caderea noptii. Dulce si captivant, o fuziune misterioasa si atragatoare a florii de iasomie scaldata in soare, cu nectar de piersici si trandafir dulce.",
      olfactory_note: "Note de varf: Floare de iasomie Note de mijloc: Trandafir confit si nectar de piersici Note de baza: Ambra, Patchouli.",
      price: 426.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwfd7f5f20/images/hi-res/all/SKU/360538_swatch.jpeg"
    },
    {
      id: 4,
      name: "Women",
      brand: "Narciso Rodriguez",
      title: "For Her",
      types: "Eau de Parfum",
      short_description: "Nascuta din simplitate si esentialitate, ghidata de feminitate si eleganta, linia For her este cadoul lui Narciso Rodriguez pentru femei si un omagiu adus frumusetii lor interioare.",
      long_description: "Nascuta din simplitate si esentialitate, ghidata de feminitate si eleganta, linia For her este cadoul lui Narciso Rodriguez pentru femei si un omagiu adus frumusetii lor interioare. Inima patentata de musc infuzata in fiecare parfum For her te poarta intr-o calatorie senzoriala.For her Eau de parfum pastreaza mosc ca nota de inima,iar piersica si trandafirul sunt adaugate pentru a face acest parfum cu adevarat catifelat. intre timp, un voal de chihlimbar moale si lemn adauga mister si profunzime compozitiei. Chiar si cu mai multa intensitate, apa de parfum For her o armonizeaza cu simplitatea calauzitoare a acestei linii.",
      olfactory_note: "Note de varf: trandafir, piersica Note de mijloc: mosc Note de baza: patchouli, ambra",
      price: 374.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwefdb23f5/images/hi-res/all/SKU/288116_swatch.jpg"
    },
    {
      id: 5,
      name: "Women",
      brand: "Kayali",
      title: "Vanilla Candy Rock Sugar l 42",
      types: "Eau de Parfum",
      short_description: "Dulce, delicios și captivant, acest parfum este o versiune mai lejera și mai proaspata a renumitului parfumum al mărcii,Vanilla Candy 28.",
      long_description: "Inspirat din dragostea Monei pentru dulciuri și notele gurmande, Vanilla Candy celebrează una dintre notele cele mai căutate în parfumerie printr-un amestec delicios de ingrediente dulci.Aromele de pere confiate si de guma de mestecat sporesc in mod ludic dulceata fructata a bomboanelor, cu o explozie de vanilie ametitoare în centru, amplificata de note calde si verzi de boabe de tonka, lemn de santal si patchouli.",
      olfactory_note: "NOTE PRINCIPALE: Pere confiate, guma de mestecat, zahar din trestie de zahar.",
      price: 472.00,
      can_in_ml: 50,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwa80227d8/images/hi-res/all/SKU/720637_swatch.jpg"
    },
    {
      id: 6,
      name: "Women",
      brand: "Dior",
      title: "Miss Dior",
      types: "Eau de Parfum",
      short_description: "Miss Dior intriga, entuziasmeaza si ne invita sa ne bucuram de dragoste si de toata frumusetea lumii.",
      long_description: "Parfumul creatorului de moda, Miss Dior Eau de Earfum, este decorat cu o noua funda textila-cativa centimetri de lux pur invelesc gatul flaconului. Noul Miss Dior Eau de Parfum arboreaza acum o funda haute couture vibranta, de inspiratie poantilista, cu o varietate de flori cu adevarat unica. La baza flaconului, motivul emblematic „picior de cocos” este gravat in sticla.",
      olfactory_note: "Note florale",
      price: 425.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw4fab0c2c/images/hi-res/all/SKU/564564_swatch.jpg"
    },
    {
      id: 7,
      name: "Women",
      brand: "TOM FORD",
      title: "Cafe Rose",
      types: "Eau de Parfum",
      short_description: "Café Rose surprinde senzualitatea neîmblânzită a unui trandafir rafinat, infuzat cu aparitia neașteptată a cafelei negre.",
      long_description: "Un indiciu delicat al plăcerii. Café Rose surprinde senzualitatea neîmblânzită a unui trandafir rafinat, infuzat cu aparitia neașteptată a cafelei negre. Esențele de trandafir turcesc și cafea dezvaluie o  profunzime senzuală, în timp ce trandafirul bulgaresc și ylang ylang emană o strălucire florala, iar coriandrul, paciuli și cardamomul picant, se incalzesc langa rășina de tămâie și acordurile lemnului de santal.",
      olfactory_note: "Note cheie:Trandafir Turcesc,Trandafir Bulgaresc,Ylang Ylang de Comore, Extract de cafea, Coriander, Patchouli",
      price: 471.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw57c14f00/images/hi-res/all/SKU/702171_swatch.jpg"
    },
    {
      id: 8,
      name: "Women",
      brand: "Armani",
      title: "Si",
      types: "Eau de Parfum",
      short_description: "Care este cel mai puternic cuvant? Sì.Puterea de a spune DA. Da pentru sine, pentru pasiune, pentru iubire si libertate.",
      long_description: "Noul parfum contrastant si hiper-senzorial este invaluit de acordurile de ambrate de chihlimbar. Este un amestec de nectar de coacaze negre, imbogatit de o inima florala catifelata si un buchet senzual de vanilie.",
      olfactory_note: "Coacaze negre, nectar, trandafir Davana, vanilie, ceai negru.",
      price: 510.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw36c7e976/images/hi-res/all/SKU/694454_swatch.jpg"
    },
    {
      id: 9,
      name: "Women",
      brand: "Armani",
      title: "Ocean di Gioia",
      types: "Eau de Parfum",
      short_description: "Scufundati-va in Ocean di Gioia, noul parfum feminin de la Giorgio Armani.",
      long_description: "Scufundati-va in Ocean di Gioia, noul parfum feminin de la Giorgio Armani. Buchetul floral stralucitor si suculent, cu note acvatice, este potrivit femeii moderne, pline de viata. Ocean di Gioia, parfumul feminin de la Giorgio Armani este un omagiu adus intinderii albastre a oceanului, oferind o priveliste revigoranta si multifatetata. Cu un duo initial suculent si in acelasi timp crocant de pere si citrice, Ocean di Gioia se deschide cu un strop de energie. Notele de mijloc sunt construite intr-un buchet cristalin si floral de iasomie, lacramioare si trandafir, ce ofera un vibe modern si senzatii revigorante, sarat-acvatice. Un parcurs vibrant, cu note lemnoase captivante de santal si muschi, adauga structura si un siaj de neconfundat. Cu liniile sale curbe inspirate de forme ale naturii, designul pur si natural al sticlei este o intruchipare moderna a viziunii lui Giorgio Armani despre eleganta esentiala, facand referire la cautarea feminitatii contemporane si autentice care il inspira. Oceanul di Gioia a fost creat pentru femeia plina de viata, naturala si ametitoare, care este in armonie cu ea insasi.",
      olfactory_note: "Note varf: para Note inima: picaturi de apa de iasomie. Note baza: lemn de santal, mosc",
      price: 380.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw3352c905/images/hi-res/all/SKU/511155_swatch.jpg"
    },
    {
      id: 10,
      name: "Women",
      brand: "Jean Paul Gaultier",
      title: "Scandal Absolu for her",
      types: "Eau de Parfum",
      short_description: "Ce Scandal absolut! Un nou Scandal de la Jean Paul Gaultier, Scandal Absolu este un parfum concentrat, care aprinde noptile pariziene. ",
      long_description: "Ce Scandal absolut! Un nou Scandal de la Jean Paul Gaultier, Scandal Absolu este un parfum concentrat, care aprinde noptile pariziene. O sticla rebela si pretioasa. Realizata intr-o simfonie fermecatoare de sectiuni oglindite si transparente, nuantele sale gradate sunt o invitatie la visare. Ingredientele pretioase ale Scandal Absolu se intalnesc intr-un parfum ciprat-ambrat, imbinand smochinul negru cu tuberoza si cu lemnul de santal. Delicios de scandalos. Paseste in noapte si devino o diva Gaultier ca nimeni alta.",
      olfactory_note: "Note de varf: Smochine, lemn de santal si tuberoza.",
      price: 868.00,
      can_in_ml: 80,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwc1cc798d/images/hi-res/all/SKU/720066_swatch.jpg"
},
{
  id: 11,
  name: "Women",
  brand: "Carolina Herrera",
  title: "Good Girl Blush Elixir",
  types: "Eau de Parfum",
  short_description: "Good Girl Blush Elixir este o interpretare senzuala si mai intensa a parfumului Good Girl Blush, intr-o sticla cu o nuanta in degradé de roz-negru.  ",
  long_description: "Good Girl Blush Elixir este o interpretare senzuala si mai intensa a parfumului Good Girl Blush, intr-o sticla cu o nuanta in degradé de roz-negru. Aceasta noua creatie olfactiva din familia Good Girl dezvaluie natura multifatetata a feminitatii moderne. Lemnoasa, misterioasa si florala, aceasta apa de parfum seducatoare este un amestec intens si incandescent de trandafir, vanilie si patchouli.",
  olfactory_note: "Note de varf: sampanie roz, floare de piersic, trandafir, ambra.",
  price: 357.00,
  can_in_ml: 30,
  image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwad05b537/images/hi-res/all/SKU/719605_swatch.jpg"
},
{
id: 12,
name: "Women",
brand: "Carolina Herrera",
title: "212 VIP Rosé",
types: "Eau de Parfum",
short_description: "212 VIP Rose este o apa de parfum delicata, cu note de sampanie roz, floare de piersic si lemn pretios.",
long_description: "212 VIP Rose este o apa de parfum delicata, cu note de sampanie roz, floare de piersic si lemn pretios. O aroma floral-lemnoasa de la Carolina Herrera care ofera emotie, seductie si bucurie.",
olfactory_note: "Note de varf: Bergamota, mandarina, ylang-ylang, rose, vanilie, patchouli.",
price: 678.00,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw85a5cfc1/images/hi-res/all/PID_principal/P1743059_principal.jpg"
},
{
id: 13,
name: "Women",
brand: "Jean Paul Gaultier",
title: "La Belle",
types: "Eau de Parfum",
short_description: "Bine ai venit in gradina Jean Paul Gaultier! ",
long_description: "Bine ai venit in gradina Jean Paul Gaultier! Apa de parfum La Belle pentru doamne te invita intr-o lume fresh-orientala, cu note de para verde, vanilie si iarba de vetiver. Cu un ambalaj nou, spectaculos, La Belle te va captiva de la prima intalnire.",
olfactory_note: "Note de varf: Bergamota, para verde, vanilie.",
price: 422.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw609d2e3c/images/hi-res/all/SKU/485322_swatch.jpg"
},
{
id: 14,
name: "Women",
brand: "Jean Paul Gaultier",
title: "Gaultier Divine",
types: "Eau de Parfum",
short_description: "Conuri si forme voluptoase. Libera si superba in corsetul ei auriu.",
long_description: "Dincolo de ambalajul exterior, magnetismul floral, marin, uimeste prin indrazneala sa. O apa de parfum solara, din alta lume: GAULTIER DIVINE. Inconjoara-te cu notele solare de crin! O bezea aerata si delicioasa echilibrata de un sarut proaspat si sarat. Si esti deja in rai! Wow ce sticla! Incredere mai presus de orice. Un corset aurit, care readuce in prim plan celebrele insertii conice inspirate din tinutele fashion Jean Paul Gaultier. Formatele 50 ml si 100 ml sunt reincarcabile (refill) si pot fi cu usurinta reincarcate utilizand formatul refill de 200 ml. Descopera GAULTIER DIVINE, noua apa de parfum de la Jean Paul Gaultier. I'M A WOMAN, WHAT'S MORE DIVINE?",
olfactory_note: "Note de varf:Acorduri sarate, crini, flori albe, bezele.",
price: 478.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw0f6f0309/images/hi-res/all/SKU/703801_swatch.jpg"
},
{
id: 15,
name: "Women",
brand: "Prada",
title: "Paradoxe",
types: "Eau de Parfum",
short_description: "PARADOXE este noul parfum feminin reincarcabil ce poarta semnatura couture Prada, este expresia esentiala a feminitatii.",
long_description: "Cu Paradoxe, vei explora reconcilierea neasteptata a contradictiilor si vei celebra expresia de sine multidimensionala si eliberarea care vine cu a nu fi niciodata la fel, mereu tu insuti. Un parfum imposibil de incadrat in tipare, care mereu se reinventeaza pe piele si evolueaza.",
olfactory_note: "Note varf: Floral, Ambrat, Moscat.",
price: 460.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwbd819a85/images/hi-res/all/SKU/617050_swatch.jpg"
},
{
id: 16,
name: "Women",
brand: "Prada",
title: "La Femme Prada",
types: "Eau de Parfum",
short_description: "Le Femme Prada aduce un omagiu neasteptatului Frangipanului. ",
long_description: "Le Femme Prada aduce un omagiu neasteptatului Frangipanului. Un floral hipersenzual, invaluit mirosul unic de ceara de albine si vanilie si imbogatit cu note de tuberoza si un vetiver, care sunt surprinzator de feminine, aducand energie pozitiva. Note: Frangipani, Miere, Tuberoza, Ylang Ylang, Vetiver, Vanilie",
olfactory_note: "Note varf:Frangipani, Miere, Tuberoza, Ylang Ylang, Vetiver, Vanilie.",
price: 490.00,
can_in_ml: 35,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw5cc2cfa8/images/hi-res/all/SKU/360491_swatch.jpg"
},
{
id: 17,
name: "Women",
brand: "TOM FORD",
title: "Lost Cherry",
types: "Eau de Parfum",
short_description: "Delicioasa apa de parfum TOM FORD PRIVATE BLEND LOST CHERRY are o deschidere gurmandă caldă și dulce.",
long_description: "Inima parfumului izbucnește în valuri de cireșe dulci-amarui, in timp ce siropul de Griotte reda dulceața texturată a fructelor voluptoase, iar florile uluitoare de Trandafir turcesc și Iasomie Sambac pătrund în simțuri și în suflet.",
olfactory_note: "Note cheie: cirese negre, boabe de tonka, migdale",
price: 966.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwc2bdaff2/images/hi-res/all/SKU/516586_swatch.jpg"
},
{
id: 18,
name: "Women",
brand: "TOM FORD",
title: "Black Orchid",
types: "Eau de Parfum",
short_description: "TOM FORD BLACK ORCHID EdP ICONIC. ELEVAT. SEDUCĂTOR. Black Orchid este un amestec bogat de mirodenii si intuneric care se invarte in jurul tau, din ce in ce mai aproape. Dezlantuie puterea sa perfecta: deopotriva rara si extraordinara.",
long_description: "TOM FORD BLACK ORCHID EdP ICONIC. ELEVAT. SEDUCĂTOR. Black Orchid este un amestec bogat de mirodenii si intuneric care se invarte in jurul tau, din ce in ce mai aproape. Dezlantuie puterea sa perfecta: deopotriva rara si extraordinara.TOM FORD Black Orchid Eau De Parfum, esenta florii de orhidee neagra intr-un parfum modern si atemporal deopotriva. Un parfum luxos si senzual, cu acorduri bogate, intunecate si o potiune seducatoare de orhidee neagra si contimente, TOM FORD BLACK ORCHIDeste deopotriva modern si atemporal.",
olfactory_note: "Note cheie: Black Truffle Bergamot Black Orchid Black Plum Noir Gourmand Accord Patchouli.",
price: 471.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwc6d00020/images/hi-res/all/SKU/159531_swatch.jpg"
},
{
id: 19,
name: "Women",
brand: "Boss",
title: "Alive",
types: "Eau de Parfum",
short_description: "Un parfum captivant, care celebreaza spiritul pozitiv si puterea femeii BOSS.",
long_description: "Un parfum captivant, care celebreaza spiritul pozitiv si puterea femeii BOSS. Florile calde, notele puternice de piele si o baza lemnoasa vibranta emana forta si feminitate, un parfum unic pentru ocazii speciale o nouă interpretare a parfumului original Boss Alive.Un parfum intens - o invitatie la a trai facand ceea ce te face sa te simti vie, puternica, increzatoare!! Bucurati-va de increderea femeii BOSS.",
olfactory_note: "Note de varf: Iasomie;  Note de inima: Vetiver; Note de baza: Piele.",
price: 457.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw0e6d9c83/images/hi-res/all/SKU/661647_swatch.jpg"
},
{
id: 20,
name: "Women",
brand: "Givenchy",
title: "L'Interdit",
types: "Eau de Parfum",
short_description: "Intrați în spațiu, dincolo de convenție și descoperiți L’Interdit Eau de Parfum pentru femei. Acest parfum curajos afirmă că îndrăzneala este cheia libertății. Nu există piedici.",
long_description: "Parfumul de flori albe pentru femei este înălțat cu un acord negru pentru a crea prima floare de subteran. Notele senzuale de floare de portocal, iasomie și tuberoză se întrepătrund cu amestecul întunecat și misterios de vetiver și patchouli. L’Interdit Eau de Parfum by Givenchy dă dependență și are o eleganță neînfricată.",
olfactory_note: "Note varf: Esenta de bergamota de Calabria, Esenta de Ghimbir Proaspat din Madagascar.",
price: 435.00,
can_in_ml: 35,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwe255ea1a/images/hi-res/all/PID_principal/P3444023_principal.jpg"
},
{
id: 21,
name: "Women",
brand: "Dior",
title: "Poison Girl",
types: "Eau de Parfum",
short_description: "Poison Girl este parfumul unei fete moderne, adorabila si irezistibila. O capcana senzuala ce atrage instantaneu si amplifica placerea pana la dependenta.",
long_description: "Poison Girl este parfumul unei fete moderne, adorabila si irezistibila. O capcana senzuala ce atrage instantaneu si amplifica placerea pana la dependenta. Un parfum floral dulce-amarui, in care portocala apetisanta este invaluita in delicioasele boabe de tonka din Venezuela, iesind apoi la iveala in senzualitatea incisiva a Trandafirului de Grasse. ",
olfactory_note: "Note varf:Portocala amara, Trandafir de Grasse, Boabe Tonka din Venezuela.",
price: 435.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw51b34f9a/images/hi-res/all/SKU/344815_swatch.jpg"
},
{
id: 22,
name: "Women",
brand: "Kayali",
title: "Yum Pistachio Gelato | 33 ",
types: "Eau de Parfum",
short_description: "Yum Pistachio Gelato | 33 Eau de Parfum Intense este o explozie delicioasa de note irezistibile si comestibile, inclusiv fistic, frisca voluptuoasă, alune prajite, rom dulce, bezele pufoase si vata de zahar spumoasa. ",
long_description: "Yum Pistachio Gelato | 33 Eau de Parfum Intense se deschide cu fatete apetisante de alune si fistic amestecate cu rom pentru o primă impresie ispititoare. In esenta, bujorul alb frumos creeaza un efect trandafiriu, asemanator mierii, in timp ce muguet ajuta la mentinerea echilibrului luxos de dulceata, prospetime si rafinament. Pe masura ce se usuca, bucura-te de o supradoza delicioasa de frisca, bezele pufoase si lemn de santal cremos pentru un parfum pentru gurmanzi incredibil de delicios.",
olfactory_note: "NOTE PRINCIPALE: Italian Bergamot,pistachio Gelato,Aluna,Rom dulce,Nucsoara,Muscata,Bujor alb.",
price: 160.00,
can_in_ml: 10,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw69261ef5/images/hi-res/all/SKU/659758_swatch.jpg"
},
{
id: 23,
name: "Women",
brand: "Kayali",
title: "Oudgasm Vanilla Oud | 36 ",
types: "Eau de Parfum",
short_description: "Dintre toate notele de parfum din lume, oudul mi-a dat întotdeauna acest sentiment incredibil de euforic, în acelasi timp transformator și expresiv - ca și cum ar exista într-un univers aparte.",
long_description: "Concepută cu pasiune și inspirată de dragostea intensă a Monei Kattan pentru oud, colecția Oudgasm de la KAYALI a fost elaborată timp de 5 ani. Aceasta celebrează numeroasele fațete ale unuia dintre cele mai nobile și mai opulente ingrediente din parfumerie. Aceste patru parfumuri unisex au fost concepute pentru a amplifica caracterul magic al oudului și pentru a explora universul infinit al posibilităților de suprapunere. Intens, senzual și luxos, fiecare parfum oferă o interpretare modernă a artei și ritualurilor de stratificare a parfumurilor din Orientul Mijlociu, pentru a fi împărtășită lumii.",
olfactory_note: "NOTE PRINCIPALE: Vanilla Sugar,Praline,Oud.",
price: 200.00,
can_in_ml: 10,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw9b949081/images/hi-res/all/SKU/694311_swatch.jpg"
},
{
id: 24,
name: "Women",
brand: "Chloé",
title: "Chloé Nomade ",
types: "Eau de Parfum",
short_description: "Femeia Chloé poarta in ea o libertate si o eleganta neschimbata si naturala. Asertiva si inspirata, ea se bazeaza pe experientele si intalnirile sale, afirmand cine este fara sa o impuna vreodata.",
long_description: "Femeia Chloé poarta in ea o libertate si o eleganta neschimbata si naturala. Asertiva si inspirata, ea se bazeaza pe experientele si intalnirile sale, afirmand cine este fara sa o impuna vreodata. In urma ei, se regaseste un parfum care o defineste oriunde merge, un parfum care ii reflecta imaginea... Nomadica, ca ea. Intalnire de forta si moliciune, fatetele acestui parfum ciprat floral ametitor sufla un vant de libertate. Caracterul intens si mineral al muschiului de stejar este invaluit de dulceata voluptoasa a prunei mirabelle. Prospetimea acestui parfum este potentata de aroma luminoasa a freziei.",
olfactory_note: "Note de varf: corcoduse Note de mijloc: frezie Note de baza: muschi de stejar.",
price: 379.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwa28cadb2/images/hi-res/all/SKU/426001_swatch.jpeg"
},
{
id: 25,
name: "Women",
brand: "Chloé",
title: "Chloé",
types: "Eau de Parfum",
short_description: "Libertate, lejeritate si feminitate: acestea sunt principiile care au stat la baza Chloe, fondata la Paris in urma cu mai bine de 60 de ani.",
long_description: "Libertate, lejeritate si feminitate: acestea sunt principiile care au stat la baza Chloe, fondata la Paris in urma cu mai bine de 60 de ani. Astazi, viziunea lui Chloé se regaseste in prêt-à-porter, accesorii si parfumuri. Chloé Eau de Parfum este un buchet generos compus din cea mai tandra parte a florilor: inimile lor. O combinatie subtila de eleganta si senzualitate, Chloé se simte ca atingerea matasii moi pe piele. Nota centrala provine din inima de trandafir. in mod surprinzator, aceasta desfasoara inflexiuni usor picante care amintesc de parfumul de zmeura. Niciodata pana acum trandafirul de la Chloé nu a afisat asemenea tonalitati fructate. Floarea de verbina adauga o dimensiune proaspata si luminos verzuie, care accentueaza inima de trandafir, pastrandu-i in acelasi timp delicatetea absoluta. Floarea de cires difuzeaza note laptoase de migdale. Pline de dulceata, acestea aduc rotunjime compozitiei. Parfumul se regaseste intr-un flacon modern, delicat, impodobit cu o panglica bej legata manual.",
olfactory_note: "Note de varf : Litchi Note de mijloc: Esenta de trandafir Damascena Note de baza: Ambra.",
price: 379.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw6b80d638/images/hi-res/all/SKU/168692_swatch.jpeg"
},
{
id: 26,
name: "Women",
brand: "Yves Saint Laurent",
title: "Black Opium ",
types: "Eau de Parfum",
short_description: "La fel de palpitant precum aroma cofeinei, acordul de cafea reda parfumului nota intensa, indrazneata si plina de adrenalina.",
long_description: "Recunoscut pentru semnatura sa florala si a parfumului de cafea, BLACK OPIUM este intr-o noua cautare a simturilor. Acordul floral emblematic de cafea devine OVER RED cu un ingredient unic si suculent: acordul de cirese. Aceasta nota de lichior captiveaza Black Opium intr-un nou univers fructat. Black Opium Eau de Parfum Over Red  este o creatie indrazneata care trezeste toate simturile.",
olfactory_note: "Note de varf: acord de para, mandarina verde, coacaze negre.Note de mijloc: iasomie, flori de portocal, ceai negru",
price: 460.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwa92c2479/images/hi-res/all/SKU/703799_swatch.jpg"
},
{
id: 27,
name: "Women",
brand: "Burberry",
title: "My Burberry",
types: "Eau de Parfum",
short_description: "Inspirat de trench coat, mostenirea stilistica si de traditie artizanala britanica, My Burberry captureaza parfumul unei gradini londoneze dupa ploaie.",
long_description: "Inspirat de trench coat, mostenirea stilistica si de traditie artizanala britanica, My Burberry captureaza parfumul unei gradini londoneze dupa ploaie.Un imens parfum floral care evidentiaza o semnatura britanica contemporana, aroma se dezvolta in jurul unor note delicate de mijloc de trandafir, evidentiate de un strop original de frunze de muscata.Notele de varf, alcatuite din mazariche si bergamota, se topesc in note centrale de gutuie aurie si de frezie, indulcite de notele de paciuli si de petale de trandafir improspatate de ploaie.",
olfactory_note: "Note de varf: Mazare dulce, bergamota Note e mijloc: Muscata, gutuie, frezie Note de baza: Patchouli, Trandafir Centifolia.",
price: 362.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwdcf556e8/images/hi-res/all/SKU/307246_swatch.jpeg"
},
{
id: 28,
name: "Women",
brand: "Burberry",
title: "My Burberry",
types: "Eau de toilette",
short_description: "Her Eau de Toilette, o apa de toaleta florala gurmanda si fructata care preia noile coduri ale casei Burberry intr-un spirit de libertate, usor si urban.",
long_description: "Her Eau de Toilette, o apa de toaleta florala gurmanda si fructata care preia noile coduri ale casei Burberry intr-un spirit de libertate, usor si urban. Un parfum cu note fructate vesele si un traseu care creeaza dependenta, Burberry Her Eau de Toilette este un parfum pentru femeile moderne, indraznete, care iubesc aventura! Parfumul este un amestec subtil de floare de bujor cu note de varf vesele de para verde, capsuni, coacaze negre si piper roz. Imbunatatita de o inima de caprifoi, crin de vale si trandafir, aroma florala fructata este indulcita de o baza captivanta de mosc si lemn de cedru.",
olfactory_note: "Note de varf : Para verde, Capsuni, Coacaze negre, Piper roz Note de mijloc : Caprifoi, Lacramioare, Trandafir Note de baza : Mosc, Lemn de cedru",
price: 383.00,
can_in_ml: 30,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw9d31dd2b/images/hi-res/all/SKU/583779_swatch.jpg"
},
{
id: 29,
name: "Women",
brand: "Narciso Rodriguez",
title: "For Her",
types: "Eau de toilette",
short_description: "Nascuta din simplitate si esentialitate, ghidata de feminitate si eleganta, linia For her este cadoul lui Narciso Rodriguez pentru femei si un omagiu adus frumusetii lor interioare.",
long_description: "Nascuta din simplitate si esentialitate; ghidata de feminitate si eleganta. Linia For her este cadoul lui Narciso Rodriguez pentru femei si un omagiu adus frumusetii lor interioare. Inima patentata de musc infuzata in fiecare parfum for her te poarta intr-o calatorie senzoriala.For her Eau de toilette se centralizeaza pe trei pulsatii olfactive. Prima pulsatie se aseamana cu cea a unei 'flori de miere'. Acesta este un mosc solar cu accente de floare de portocal si osmanthus. Mai departe in parfum, pulsatia 'lumina de chihlimbar' foloseste moscurile in cea mai unica maniera, moliciunea sa invaluind femeia care il poarta cu ambrelyn si vanilie. in cele din urma, un puls 'lemnos' duce mai departe moscurile cu note de vetiver, amplificand senzualitatea parfumului.",
olfactory_note: "Nota de varf:floare de osmanthus ,nota de mijloc: mosc, note de baza:patchouli, chihlimbarina",
price: 437.35,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwa86e9e91/images/hi-res/all/SKU/56131_swatch.jpg"
},
    {
      id: 30,
      name: "Men",
      brand: "Armani",
      title: "Stronger With You",
      types: "Eau de toilette",
      short_description: "Stronger With You este perechea lui Because It's You. Manifestul contemporan Emporio al perechii perfecte, parfumul lui este imprevizibil si surprinde prin aroma de cardamon si accentele de salvie si castana coapta. Senzual si romantic, magnetizant.",
      long_description: "Stronger With You este perechea lui Because It's You. Manifestul contemporan Emporio al perechii perfecte, parfumul lui este imprevizibil si surprinde prin aroma de cardamon si accentele de salvie si castana coapta. Senzual si romantic, magnetizant.",
      olfactory_note: "Note varf: cardamom, frunze de violete, menta, piper roz. Note mijloc: pepene galben, salvie, ananas. Note baza: vanilie, castan, Amberwood, cedru",
      price: 340.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw3f94c66c/images/hi-res/all/SKU/392282_swatch.jpg"
    },
    {
      id: 31,
      name: "Men",
      brand: "Armani",
      title: "Armani Code",
      types: "Eau de toilette",
      short_description: "ARMANI CODE EAU DE TOILETTE intra intr-o noua era cu masculinitatea sa orientata spre viitor, dar si cu o noua sticla reincarcabila.",
      long_description: "Parfumul ARMANI CODE de la GIORGIO ARMANI creeaza o stare de masculinitate seducatoare, dar in acelasi timp si sensibila datorita contrastelor elegante ale ingredientelor sale rafinate.Compozitia parfumului evidentiaza opozitii captivante, deoarece prospetimea mandarinei verzi se imbina cu inima aromata a lavandei, in timp ce senzualitatea si notele ispititoare ale boabelor absolute de Tonka se imbina cu inima reconfortanta din lemnul de cedru.<br>",
      olfactory_note: "Note varf: Fougere, oriental-picant,Ulei de grepfrut citric,Esenta de muscata si lavanda,Vanilia Bourbon",
      price: 450.00,
      can_in_ml: 50,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw52abcd43/images/hi-res/all/PID_principal/P10047820_principal.jpg"
    },
    {
      id: 32,
      name: "Men",
      brand: "Azzaro",
      title: "The Most Wanted",
      types: "Eau de toilette",
      short_description: "Azzaro The Most Wanted Eau de Toilette Intense este o fotografie palpitantă de viață pentru bărbatul care îndrăznește să fie el însuși fără scuze. ",
      long_description: "Azzaro The Most Wanted Eau de Toilette Intense este o fotografie palpitantă de viață pentru bărbatul care îndrăznește să fie el însuși fără scuze. Un parfum Lemnos Aromatic Fougere, care asigură 9 ore de senzație de prospețime*. Testat și aprobat. *Test de consum pe 65 de bărbați",
      olfactory_note: "Notă de vârf : Esență de bergamotă.Notă de bază : Acord Liqueur de Mousse. Notă de inimă : Cœur de Lavande de Provence",
      price: 354.00,
      can_in_ml: 50,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw651bae58/images/hi-res/all/PID_principal/P10057811_principal.jpg"
    },
    {
      id: 33,
      name: "Men",
      brand: "Dior",
      title: "Sauvage",
      types: "Eau de toilette",
      short_description: "O compozitie de o prospetime deosebita, dictata de un nume ce a devenit emblematic",
      long_description: "O compozitie de o prospetime deosebita, dictata de un nume ce a devenit emblematic. Este ceea ce si-a dorit Francois Demachy, Parfumier Creator al Casei Dior: brut si nobil in acelasi timp. Ingredientele naturale, selectate cu mare grija, prevaleaza in mod deosebit. Notele de varf sunt radiante, date de prospetimea suculenta si exploziva a bergamotei din Reggio din Calabria. Ambroxanul, obtinut din pretioasa ambra, dezlantuie un puternic parfum lemnos. Sauvage este un act de creatie inspirat de spatiile larg deschise. Un cer de un albastru intens ce domina un desert stancos, incalzit de un soare stralucitor.",
      olfactory_note: "Note condimentate si lemn de ambra",
      price: 400.00,
      can_in_ml: 30,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw3c8c9e0c/images/hi-res/all/SKU/541801_swatch.jpg"
    },
    {
      id: 34,
      name: "Men",
      brand: "Prada",
      title: "L'Homme Prada",
      types: "Eau de toilette",
      short_description: "Un parfum inconfundabil in care aromele se alatura intr-o compozitie completa, iar contrastele creeaza un rezultat unic. Clasic masculin si in acelasi timp proaspat si extrem de senzual, potrivit pentru fiecare zi. ",
      long_description: "Un parfum inconfundabil in care aromele se alatura intr-o compozitie completa, iar contrastele creeaza un rezultat unic. Clasic masculin si in acelasi timp proaspat si extrem de senzual, potrivit pentru fiecare zi. Jucandu-se cu notele masculine clasice, Prada L'Homme Apa de Toaleta ofera o interpretare moderna completa a ingredientelor traditionale. Acordurile fougere sunt prezente in Neroli, Muscata si Paciuli, iar semnatura Prada ofera un caracter androgin si intersanjabil adus de elemente precum floarea de Iris si Chihlimbar. Note: Seminte de Morcov, Piper Negru, Cardamom, Mate, Iris, Patchouli, Lemn de Santal, Acord de chihlimbar, Ambrofix.",
      olfactory_note: "Note varf: Seminte de Morcov, Piper Negru, Cardamom, Maté, Iris, Patchouli, Lemn de Santal, Acord de chihlimbar, Ambrofix.",
      price: 500.00,
      can_in_ml: 50,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw977c486f/images/hi-res/all/SKU/360495_swatch.jpg"
    },
    {
      id: 35,
      name: "Men",
      brand: "Yves Saint Laurent",
      title: "La Nuit de L'Homme",
      types: "Eau de toilette",
      short_description: "Un parfum proaspat-condimentat, plin de tensiuni si contraste olfactive, pentru un barbat seducator, elegant, increzator si de succes.",
      long_description: "Un parfum proaspat-condimentat, plin de tensiuni si contraste olfactive, pentru un barbat seducator, elegant, increzator si de succes.O legatura puternica intre prospetimea notelor de citrice puse in valoare de aromele de lamaie si bergamota, intensitatea notelor condimentate si caldura puternica a notelor lemnoase. Extractul de piper negru si coaja citricelor se contopesc cu notele opulente de vetiver si cedru, simboluri ale fortei si virilitatii. O noapte irezistibila si plina de senzualitate rafinata.",
      olfactory_note: "Note varf: cardamom, frunze de violete, menta, piper roz. Note mijloc: pepene galben, salvie, ananas. Note baza: vanilie, castan, Amberwood, cedru",
      price: 490.00,
      can_in_ml: 60,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw6dbe9c0a/images/hi-res/all/SKU/186318_swatch.jpg"
    },
    {
      id: 36,
      name: "Men",
      brand: "Armani",
      title: "Eau de Cèdre",
      types: "Eau de toilette",
      short_description: "O tenta informala. Un parfum pentru gentleman-ul modern.Bergamota spumanta, lamaia si frunza de violeta isi fac simtita prezenta printre notele impunatoare de cardamom Pure Jungle Essence, inainte de a deveni mai calde la contactul cu chimionul condimentat si salvia crocanta.",
      long_description: "O tenta informala. Un parfum pentru gentleman-ul modern.Bergamota spumanta, lamaia si frunza de violeta isi fac simtita prezenta printre notele impunatoare de cardamom Pure Jungle Essence, inainte de a deveni mai calde la contactul cu chimionul condimentat si salvia crocanta. La baza parfumului stau note de esenta de cedru si extract de ceai negru, care se intalnesc cu puterea maxima de seductie a unui acord velurat si fin.",
      olfactory_note: "Note varf: bergamota, lamaie, salvie. Note mijloc: cardamom, frunze de violete, chimion.Note baza: velur, ceai negru, tonuri lemnoase, cedru",
      price: 471.50,
      can_in_ml: 100,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw10784847/images/hi-res/all/PID_principal/P2300010_principal.jpg"
    },
    {
      id: 37,
      name: "Men",
      brand: "Boss",
      title: "The Scent",
      types: "Eau de toilette",
      short_description: "BOSS The Scent este o apa de toaleta seducatoare pentru barbati de la BOSS Fragrances. Un parfum irezistibil care invadeaza mintea si lasa o amprenta durabila.",
      long_description: "BOSS The Scent este o apa de toaleta seducatoare pentru barbati de la BOSS Fragrances. Un parfum irezistibil care invadeaza mintea si lasa o amprenta durabila. BOSS The Scent se mandreste cu un ingredient exclusiv din Africa de Sud, fructul afrodisiac Maninka, ale carui fatete complexe fac aluzie la rhum si fructul pasiunii. Asezat pe o baza virila de piele, efectul sau este puternic, original, care nu va fi uitat niciodata. Parfumul se deschide pe prospetimea afrodisiaca si picanta a ghimbirului, care ofera barbatului care il poarta o energie stimulanta. In nota de inima, dulceata exotica afrodiziaca a fructului african Maninka invadeaza simturile. Bogatia afumata si adictiva a pielii adauga o caldura seducatoare persistenta notei de baza si transmite masculinitate pura si magnetica. Flaconul prezinta un suc evocator de chihlimbar, asezat intr-o cusca de argint, ca si cum ar capta spiritul seductiei inainte de a-si dezlantui puterea dinamica.",
      olfactory_note: "Note de varf: mandarina, bergamota, ghimbir Note de mijloc: lavanda, fruct Maninka Note de baza: piele, tonuri lemnoase.",
      price: 513.00,
      can_in_ml: 50,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw7e03e004/images/hi-res/all/SKU/332117_swatch.jpeg"
    },
    {
      id: 38,
      name: "Men",
      brand: "Givenchy",
      title: "Gentleman",
      types: "Eau de toilette",
      short_description: "Stânjenelul delicat se amestecă cu lemnul de cedru puternic în acest parfum bărbătesc captivant.",
      long_description: "Stânjenelul delicat se amestecă cu lemnul de cedru puternic în acest parfum bărbătesc captivant. Un omagiu adus lui Hubert de Givenchy, Gentleman Eau de Toilette pentru bărbați combină siguranța cu tandrețea pentru a încapsula caracteristicile definitorii ale gentlemanului desăvârșit.<br><br>Produsă în Franța în Atelierele Givenchy, Givenchy Gentleman Eau de Toilette pentru bărbați este o explozie de senzații care se deschid cu bergamota strălucitoare, busuioc și cardamon. Sofisticarea delicată a stânjenelului albastru proaspăt se dezvăluie apoi în parfumul bărbătesc îmbogățit cu lemn de cedru puternic și cumarină caldă. Contrastul puternic face ca acest parfum aromat floral lemnos să lase în urmă o senzație care se transformă în adicție.",
      olfactory_note: "Note varf: floral-lemnos.",
      price: 455.00,
      can_in_ml: 60,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwa8db5377/images/hi-res/all/SKU/543384_swatch.jpg"
    },
    {
      id: 39,
      name: "Men",
      brand: "Carolina Herrera",
      title: "Bad Boy Power Up Spray Fresh",
      types: "Eau de toilette",
      short_description: "Acest cooling Power Up Spray aduce ingredientele indraznete din parfumul BAD BOY intr-un recipient indestructibil, ideal pentru o aplicare on-the-go.",
      long_description: "Acest cooling Power Up Spray aduce ingredientele indraznete din parfumul BAD BOY intr-un recipient indestructibil, ideal pentru o aplicare on-the-go. Fara propulsori, acest produs foloseste aer comprimat pentru a limita impactul negativ asupra mediului. Ingredientele te poarta intr-o calatorie olfactiva presarata cu piper alb si negru, seminte tonka, cacao, bergamota sau lemn de cedru. Foloseste-l de fiecare data, oriunde. Acelasi BAD BOY, acum Power Up Spray.",
      olfactory_note: "Note varf: piper alb&roz, bergamota, lem de cedru, salvie, seminte de tonka.",
      price: 462.00,
      can_in_ml: 100,
      image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw2ee4a92a/images/hi-res/all/SKU/528593_swatch.jpg"
},
{
  id: 40,
  name: "Men",
  brand: "Carolina Herrera",
  title: "212 Vip Black",
  types: "Eau de Parfum",
  short_description: "212 VIP BLACK reprezinta prima apa de parfum barbateasca a liniei 212 VIP semnata Carolina Herrera.78",
  long_description: "212 VIP BLACK reprezinta prima apa de parfum barbateasca a liniei 212 VIP semnata Carolina Herrera. Absintul si levantica aduc prospetimea, veselia, in timp ce ambra, moscul si semintele de tonka completeaza acordurile puternice, sexy, macante, de piele. Completeaza-ti gasca olfactiva sau intra acum in clubul VIP - VERY INCREDIBLE PEOPLE.",
  olfactory_note: "Note de varf: absint, lavanda, acord de piele, vanilie, mosc.",
  price: 439.00,
  can_in_ml: 50,
  image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw4a45b2ef/images/hi-res/all/SKU/401045_swatch.jpg"
},
{
id: 41,
name: "Men",
brand: "Jean Paul Gaultier",
title: "Le Male Le Parfum",
types: "Eau de Parfum",
short_description: "Bine ai venit la bord! Jean Paul Gaultier te invita sa descoperi noua apa de parfum intensa pentru domni Le Male Le Parfum.",
long_description: "Creatorul reinventeaza simbolul marinarului odata cu lansarea noului parfum intens Le Male Le Parfum si ii ofera un nou statut, de capitan! Cu un sacou negru si insertii aurii de ofiter, noul Le Male Le Parfum trece la carma liniei de parfumerie cu stil si eleganta. Vantul aspru al cardamonului in panzele sale, prospetimea lavandei, notele de mijloc de floare de iris, toate se contopesc cu aroma puternica a vaniliei. O odisee olfactiva care seduce toate simturile. Sticla, de un negru intens, elegant, mat, cu linii bine definite si insertii aurii, se impune cu respect, ca un leader respectat.",
olfactory_note: "Note de varf:cardamon, lavanda, iris, vanilie",
price: 493.00,
can_in_ml: 75,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwebb18728/images/hi-res/all/SKU/515091_swatch.jpg"
},
{
id: 42,
name: "Men",
brand: "Azzaro",
title: "The Most Wanted",
types: "Eau de Parfum",
short_description: "Cu The Most Wanted Perfume, ia totul si descopera o intensitate care transcende cuvintele. ",
long_description: "Inflacarat si intens, acest parfum pentru barbati te invita sa eliberezi energia arzatoare din tine ca niciodata inainte. Acordul sau de caramel care se topeste, amestecat cu senzualitatea vaniliei Bourbon, dezvaluie o semnatura magnetica ultra-dependenta. Intregul lucru este accentuat de un acord lemnos incandescent si un cocktail picant, pentru un traseu de foc de lunga durata.",
olfactory_note: "Notă de vârf : Red Ginger, incandescent woods accord, Bourbon Vanilla.",
price: 379.00,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw3140c4f4/images/hi-res/all/SKU/609405_swatch.jpg"
},
{
id: 43,
name: "Men",
brand: "Azzaro",
title: "Azzaro Wanted",
types: "Eau de Parfum",
short_description: "Esti pregatit sa faci fata oricarei provocari? Azzaro prezinta Wanted, o apa de toaleta extrem de masculina pentru barbatul extravagant, hedonist, care stie cum sa profite de sansele sale si care sfideaza destinul.",
long_description: "Esti pregatit sa faci fata oricarei provocari? Azzaro prezinta Wanted, o apa de toaleta extrem de masculina pentru barbatul extravagant, hedonist, care stie cum sa profite de sansele sale si care sfideaza destinul. Azzaro Wanted combina prospetimea cardamonului, eleganta lemnoasa a vetiverului si caldura armonioasa a boabelor de tonka intr-o sticla sofisticata in forma de butoias pentru cartuse... ca un simbol al libertatii. Familia olfactiva: proaspat-lemnos.",
olfactory_note: "Notă de vârf :Lemnos.",
price: 480.00,
can_in_ml: 100,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw62cd9aa9/images/hi-res/all/SKU/355660_swatch.jpg"
},
{
id: 44,
name: "Men",
brand: "Prada",
title: "Luna Rossa Ocean",
types: "Eau de Parfum",
short_description: "Noul Luna Rossa Ocean Le Parfum este un parfum care te incurajeaza sa iti depasesti limitele pentru a fi deschis catre noi orizonturi.",
long_description: "Luna Rossa OCEAN Le Parfum este un parfum puternic si sofisticat, ambery fougère. Se deschide cu o esenta viguroasa si proaspata de lamaie ce contrasteaza acordul sofisticat si magnetic al sofranului si notelor smoky de lemn de stejar. Un parfum augumentat de o extractie de ingrediente naturale care deschide noi orizonturi. ​",
olfactory_note: "Note varf:Lămâie, șofran, lemn de stejar.",
price: 590.00,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw7f367b24/images/hi-res/all/SKU/731306_swatch.jpeg"
},
{
id: 45,
name: "Men",
brand: "Boss",
title: "BOSS Bottled Triumph Elixir",
types: "Eau de Parfum",
short_description: "2023 marcheaza cea de-a 25-a aniversare a unui icon al parfumurilor, originalul BOSS Bottled Eau de Toilette. Pentru a sarbatori aceasta ocazie intr-un stil spectaculos.",
long_description: "Noul Elixir capteaza atentia prin concentratia sa ridicata de ingrediente opulente. Notele de varf de tamaie si esenta de cardamon emit o impresie calduroasa si vibranta, in timp ce inima de vetiver si patchouli atrage cu o amprenta pamanteasca. BOSS Bottled Elixir se dezvolta dezvaluind o baza de esenta de cedru si absolut de labdanum, emanand un carism puternic si lemnos si o explozie a masculinitatii indraznete.",
olfactory_note: "Note de baza: Cardamon; Note de mijloc: Vetiver, Patchouli; Note de varf: Lemn de santal, Labdanum.",
price: 557.00,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw7f10f1b2/images/hi-res/all/SKU/697641_swatch.jpg"
},
{
id: 46,
name: "Men",
brand: "Boss",
title: "BOSS Bottled",
types: "Eau de Parfum",
short_description: "O masculinitate intensa si rafinata este dezvaluita in BOSS Bottled Eau de Parfum. ",
long_description: "O masculinitate intensa si rafinata este dezvaluita in BOSS Bottled Eau de Parfum. Creata pentru barbatii ambitiosi si motivati, gata sa accepte orice provocare care le iese in cale, aceasta compozitie nobila aduce o noua intensitate la caldura si vibratia semnaturii atemporale BOSS Bottled. Simturile sunt trezite de o explozie de mar si bergamota, contrastata cu esenta de piper negru. Inima picanta se desfasoara cu uleiuri calde si captivante de cardamom si scortisoara. Exudand un echilibru puternic de forta si sofisticare, notele de baza de vetiver intunecat si mosc evolueaza in timp, oferind o semnatura de piele si fumuriu.",
olfactory_note: "Note de varf: Mar, bergamota Note de mijloc : Cardamom, Scortisoara Note de baza: Vetiver, Maslin.",
price: 422.25,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwe6d0b676/images/hi-res/all/SKU/528750_swatch.jpeg"
},
{
id: 47,
name: "Men",
brand: "Givenchy",
title: "L'Interdit",
types: "Eau de Parfum",
short_description: "Încălcând toate regulile și dovedind o îndrăzneală antrenantă, L'Interdit Eau de Parfum Intense pentru femei de la Givenchy te face să simți fiorul lucrurilor interzise, tinzând la lucruri tot mai îndrăznețe.",
long_description: "Acest parfum opulent și intens pentru femei se deschide cu o exultare de floare de portocal și tuberoză. Simțurile sunt captivate de vanilia suavă și de susanul negru neașteptat. Și, în notele sale de mijloc, amestecul lemnos de vetiver și patchouli transformă L'Interdit Eau de Parfum Intense by Givenchy în cel mai negru, mai intens Underground Flower.",
olfactory_note: "Note varf:Vetiver și patchouli.",
price: 439.00,
can_in_ml: 35,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw0c154e68/images/hi-res/all/SKU/517337_swatch.jpg"
},
{
id: 48,
name: "Men",
brand: "Dior",
title: "Sauvage",
types: "Eau de Parfum",
short_description: "Sauvage Elixir este un parfum cu o concentratie extraordinara*, imbibat de prospetimea emblematica Sauvage, cu o inima condimentata si o esenta de lavanda „personalizata”, o combinatie de note lemnoase dulci si blande care formeaza semnatura sa puternica, remarcabila si captivanta.",
long_description: "Sauvage Elixir este un parfum cu o concentratie extraordinara*, imbibat de prospetimea emblematica Sauvage, cu o inima condimentata si o esenta de lavanda „personalizata”, o combinatie de note lemnoase dulci si blande care formeaza semnatura sa puternica, remarcabila si captivanta.François Demachy, Parfumier-creator Dior, a compus parfumul Sauvage Elixir ca pe un lichior fin cu ingrediente exceptionale. Acest nivel ridicat de concentratie a putut fi atins datorita calitatii exceptionale a materiilor prime: Sauvage Elixir este un parfum la fel de unic si de rar ca „luna rosie” pe cerul noptii.",
olfactory_note: "Note condimentate si extract de vanilie",
price: 461.25,
can_in_ml: 60,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwda198a3f/images/hi-res/all/SKU/558095_swatch.jpg"
},
{
id: 49,
name: "Men",
brand: "Yves Saint Laurent",
title: "Y",
types: "Eau de Parfum",
short_description: "PROFUNZIME & INTENSITATE Parfumul Y, sub semnatura sa fresh, exploreaza noi orizonturi cu o versiune mai profunda si intensa: Y Eau de Parfum Intense de la Yves Saint Laurent. ",
long_description: "PROFUNZIME & INTENSITATE Parfumul Y, sub semnatura sa fresh, exploreaza noi orizonturi cu o versiune mai profunda si intensa: Y Eau de Parfum Intense de la Yves Saint Laurent. ",
olfactory_note: "Note de varf:Lavanda, salvie, ienupar, patchouli",
price: 660.00,
can_in_ml: 60,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw075aabb6/images/hi-res/all/SKU/659483_swatch.jpg"
},
{
id: 50,
name: "Men",
brand: "Burberry",
title: "Burberry Hero",
types: "Eau de Toilette",
short_description: "Un nou spirit masculin care exploreaza codurile casei dualitatii si puterea regnului animal. Un om in cautarea transformarii si metamorfozei ca un nou eroism modern. ",
long_description: "Un nou spirit masculin care exploreaza codurile casei dualitatii si puterea regnului animal. Un om in cautarea transformarii si metamorfozei ca un nou eroism modern. Viziunea lui Burberry despre eroismul modern este provocarea stereotipurilor traditionale ale masculinitatii si imputernicirea omului de a se transforma pentru a gasi curajul de a imbratisa cine esti cu adevarat, de a deveni extraordinar.   Un om nou. Un erou.Enigmatic si aventuros, Burberry Hero imbratiseaza dualitatea: forta si subtilitate, putere si compasiune, atletism si creativitate.  Burberry Hero Fragrance este o combinatie captivanta de putere si prospetime, semnificand dualitatea omului modern de putere si sensibilitate.  ",
olfactory_note: "Note de varf: bergamota, lamaie, cardamom Note de mijloc: ienupar, nucsoara, lavanda, piper negru Note de baza: lemn de cedru.",
price: 447.00,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw3f10fe01/images/hi-res/all/SKU/519765_swatch.jpeg"
},
{
id: 51,
name: "Men",
brand: "Narciso Rodriguez",
title: "For Him Bleu Noir",
types: "Eau de Parfum",
short_description: "Parfumul pentru barbati BLEU NOIR PARFUM de la Narciso Rodriguez este o versiune mai intensa si mai rafinata a parfumurilor iconice din linia for him bleu noir - apa de toaleta si apa de parfum. ",
long_description: "Parfumul pentru barbati BLEU NOIR PARFUM de la Narciso Rodriguez este o versiune mai intensa si mai rafinata a parfumurilor iconice din linia for him bleu noir - apa de toaleta si apa de parfum. Compozitia se deschide cu notele de varf citrice ascutite de bergamota italiana si mandarina, eliberand energie proaspata in contrast cu moscul senzual si invaluitor care pulsa in inima parfumului. ",
olfactory_note: "Note de varf: bergamota, iris Note de mijloc: Inima de mosc Note de baza: piele intoarsa, boabe de Tonka",
price: 526.00,
can_in_ml: 50,
image: "https://www.sephora.ro/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dw936a2dd6/images/hi-res/all/SKU/581843_swatch.jpg"
},
    {
      id: 52,
      name: "Home",
      brand: "Rituals...",
      title: " The Ritual of Karma",
      types: "Candle",
      material: "sticla",
      short_description: "Creati o atmosfera calda, de vara, in locuinta dvs. cu lumanarea parfumata The Ritual of Karma.",
      long_description: "Creati o atmosfera calda, de vara, in locuinta dvs. cu lumanarea parfumata The Ritual of Karma. Aceasta are o aroma dulce si delicata de lotus sacru, combinat cu ceaiul alb hranitor, pentru ca dvs. sa va puteti bucura de lumanare timp de pana la 50 de ore. Lasati notele insorite si racoritoare sa va transporte intr-un paradis indepartat. Aceasta compozitie revigoranta se deschide cu note initiale de bergamota si grepfrut, continuand exuberant cu acorduri centrale de lotus, floare de portocal si liliac. Tusele finale lemnoase de mosc si lemn de santal prelungesc parfumul de seara estivala ore in sir. Pentru a imbogati experienta parfumului, combinati cu betisoarele parfumate The Ritual of Karma pentru o atmosfera speciala de vara.",
      olfactory_note: "Note varf: bergamota si grepfrut.",
      price: 125.00,
      can_in_g: 250 ,
      image: "https://media.douglas.ro/ro/thumbnail/42/9c/56/1663572494/8719134132564-1_1280x1280.jpg"
    },
    {
      id: 53,
      name: "Home",
      brand: "Rituals...",
      title: " The Ritual of Jing Scented",
      types: "Candle",
      material: "sticla",
      short_description: "Învăluiți-vă cu o senzație de pace interioară atunci când aprindeți această lumânare parfumată de lux.",
      long_description: "Învăluiți-vă cu o senzație de pace interioară atunci când aprindeți această lumânare parfumată de lux. Lumânarea parfumată The Ritual of Jing este îmbogățită cu parfumul floral, cald, de lotus sacru și fruct de jujube. Emană o aromă liniștitoare și calmantă și reprezintă un accesoriu natural și elegant pentru locuința dumneavoastră. Lumânarea durează până la 50 de ore.",
      olfactory_note: "Note varf: lotus sacru și fruct de jujube.",
      price: 125.00,
      can_in_g: 260 ,
      image: "https://media.douglas.ro/ro/thumbnail/80/68/6d/1673667407/8719134150773-1gixxwv2p300vf_1280x1280.jpg"
    },
    {
      id: 54,
      name: "Home",
      brand: "Rituals...",
      title: " The Ritual of Sakura Scented",
      types: "Candle",
      material: "sticla",
      short_description: "Luminati calea spre un nou inceput cu aceasta lumanare, luxurianta parfumata.",
      long_description: "Luminati calea spre un nou inceput cu aceasta lumanare, luxurianta parfumata. Inspirat din parfumul revitalizant al florii de cires si al laptelui de orez. Lumanarea dureaza pana la 50 de ore.",
      olfactory_note: "Note varf:  flori de cires, lapte de orez.",
      price: 101.00,
      can_in_g: 290 ,
      image: "https://media.douglas.ro/ro/thumbnail/f0/db/80/1663572743/8719134071535_2_1280x1280.jpg"
    },
    {
      id: 55,
      name: "Home",
      brand: "Rituals...",
      title: " Rituals Private Collection Sweet Jasmine Scented ",
      types: "Candle",
      material: "sticla",
      short_description: "Creati o atmosfera de calm in locuinta dvs., cu lumanarea cu parfum de iasomie dulce din colectia noastra Private Collection. ",
      long_description: "Creati o atmosfera de calm in locuinta dvs., cu lumanarea cu parfum de iasomie dulce din colectia noastra Private Collection. Notele initiale amintesc de aroma intensa si proaspata a citricelor si a fructelor de padure, care se continua cu tonuri elegante de bujor si lacramioara. Santalul confera un plus de caldura si eleganta acestui parfum.Borcanul din sticla, de culoarea sampaniei, este o completare perfecta a oricarui decor, din locuinta dumneavoastra ori a persoanei careia i-l oferiti cadou. Cand s-a golit, curatati urmele de lumanare si folositi-l pentru a pastra flori, creioane sau pensule.",
      olfactory_note: "Note varf: citric, fructat.",
      price: 197.00,
      can_in_g: 360 ,
      image: "https://media.douglas.ro/ro/thumbnail/26/33/bc/1716819505/8719134158243_1920x1920.jpg"
    },
    {
      id: 56,
      name: "Home",
      brand: "Rituals...",
      title: " Rituals Sweet Jasmine Scented",
      types: "Candle",
      material: "sticla",
      short_description: "Creați o atmosferă de calm în locuința dumneavoastră, cu lumânarea cu parfum de iasomie dulce, din colecția noastră Private Collection.",
      long_description: "Vegetarian, fara acetona, fara amoniac, fara comedogen, fara conservanti, fara ftalati, fara gluten, fara ingrediente uleioase, fara lactoza, fara microplastic, fara paraben, fara parafina, fara pigmenti si coloranti, fara silicon, fara sulfati, fara ulei de palmier, fara urme de nuci, non-alcoolic, pentru pielea sensibila.",
      olfactory_note: "Note varf: citric, fructat.",
      price: 193.00,
      can_in_g: 360 ,
      image: "https://media.douglas.ro/ro/thumbnail/d9/d6/74/1684763562/8719134161786_1920x1920.jpg"
    },
    {
      id: 57,
      name: "Home",
      brand: "Rituals...",
      title: " Rituals Private Collection Savage Garden Scented",
      types: "Candle",
      material: "sticla",
      short_description: "Creați o atmosferă relaxantă cu această lumânare unică și intens aromată din Colecția noastră privată.",
      long_description: "Experimentati un moment de liniste pura atunci cand aprindeti aceasta lumanare luxurianta din Colectia privata. Pe baza de vetiver verde, cunoscut si ca „uleiul relaxarii”. Lumanarea va poate ajuta sa va relaxati timp de pana la 60 de ore.",
      olfactory_note: "Note varf: aromatice, proaspat, verde.",
      price: 197.00,
      can_in_g: 360 ,
      image: "https://media.douglas.ro/ro/thumbnail/48/05/b9/1712672198/8719134156799_2_1920x1920.jpeg"
    }
]
app.get('/products', (req, res) => {
    res.json(products);
});

app.get('/products/:id', (req, res) => {
    const productId = parseInt(req.params.id); 

    const product = products.find(prod => prod.id === productId);

    if (!product) {
        return res.status(404).json({ error: 'Product not found' });
    }

    res.json(product);
});


const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Server is running on http://localhost:${port}`));
